
name: build-dawn

on:
  push:
    branches:
      - main

concurrency:
  # Use github.run_id on main branch
  # Use github.event.pull_request.number on pull requests, so it's unique per pull request
  # Use github.ref on other branches, so it's unique per branch
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  info:
    runs-on: ubuntu-24.04
    outputs:
      DAWN_COMMIT: ${{ steps.info.outputs.DAWN_COMMIT }}
      BUILD_DATE: ${{ steps.info.outputs.BUILD_DATE }}
    steps:
      - name: Get Latest Commit Id
        id: info
        run: |
          echo DAWN_COMMIT=`git ls-remote https://github.com/SoapyMan/dawn.git all-fixes-merged | awk '{ print $1 }'` >> ${GITHUB_OUTPUT}
          echo BUILD_DATE=`date +'%Y-%m-%d'` >> ${GITHUB_OUTPUT}
          
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows_Latest_MSVC",
            os: windows-latest,
            artifact_type: ".zip",
            artifact_content_type: application/zip
          }
        - {
            name: "Ubuntu_Latest_GCC",
            os: ubuntu-latest,
            artifact_type: "tar.gz",
            artifact_content_type: application/x-tgz
          }
    env:
      DAWN_COMMIT: ${{ needs.info.outputs.DAWN_COMMIT }}
      BUILD_DATE: ${{ needs.info.outputs.BUILD_DATE }}

    steps:
      - name: Install dependencies
        if: startsWith(matrix.config.name, 'Ubuntu')
        run: |
          sudo apt update
          sudo apt install cmake pkg-config libgl-dev libx11-xcb-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev wayland-protocols libwayland-dev libxkbcommon-dev

      - uses: actions/checkout@v2
      
      - name: Install Windows SDK v10.0.26100.0
        if: startsWith(matrix.config.name, 'Windows')
        id: win-sdk
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --quiet --force --norestart --add Microsoft.VisualStudio.Component.Windows11SDK.26100

      - name: build
        if: startsWith(matrix.config.name, 'Windows')
        id: build-win
        shell: cmd
        run: build.cmd

      - name: build
        if: startsWith(matrix.config.name, 'Ubuntu')
        id: build-linux
        shell: bash
        run: ./build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dawn-${{ matrix.config.name }}-${{ env.BUILD_DATE }}
          path:  |
              *.dll
              *.lib
              *.so
              *.h
          if-no-files-found: error
          compression-level: 4